networks:
  ai_service:
    name: ai-service-network
    driver: bridge
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - ./redis:/data
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_PORT=6379
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 15s
      timeout: 5s
      retries: 5
    command: [ "redis-server" ]
    networks:
      - ai_service

  langgraph-api:
    image: junior_bot
    ports:
      - "8123:8123"
    restart: unless-stopped
    networks:
      - ai_service
    depends_on:
      redis:
        condition: service_healthy
      postgres_rummikub_db:
        condition: service_healthy
    environment:
      - PORT=8123

  postgres_rummikub_db:
    image: postgres:15.8-alpine
    environment:
      POSTGRES_DB: 'rummikub_db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    healthcheck:
      test: pg_isready -U postgres
      start_period: 10s
      timeout: 1s
      retries: 5
      interval: 5s
    ports:
      - '54326:5432'
    networks:
      - ai_service
    volumes:
      - ./rummikub/postgres/data:/var/lib/postgresql/data
      - ./init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql

  ollama:
    image: ollama/ollama:0.5.3
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
    volumes:
      - ./ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "ollama", "list" ]
      interval: 15s
      timeout: 5s
      retries: 5
    entrypoint: [ "/usr/bin/bash", "/entrypoint.sh" ]
    networks:
      - ai_service